spring.application.name=Online-Food-Ordering
# Recommended: Let Spring Boot auto-detect the driver
spring.datasource.url=jdbc:mysql://localhost:3306/Foodcart
spring.datasource.username=root
spring.datasource.password=Vishal@123

# Optional: Explicitly naming the driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
